name: Build YouTube Version (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to pass to build-version.sh (or "auto")'
        required: true
        default: '20.21.37'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Run build-version.sh
        working-directory: revanced-magisk
        run: |
          set -eux
          chmod +x ./build-version.sh
          ./build-version.sh "${{ github.event.inputs.version }}"

      - name: Debug - show revanced-magisk/build (if exists)
        run: |
          echo "=== revanced-magisk/build top-level ==="
          ls -la revanced-magisk/build || echo "revanced-magisk/build not present"
          echo "=== show any zips/apks in build (detailed) ==="
          find revanced-magisk/build -type f \( -iname '*.apk' -o -iname '*.zip' \) -exec du -b {} + 2>/dev/null || true
          echo "=== if nothing above, show top-level of revanced-magisk ==="
          ls -la revanced-magisk || true

      - id: collect
        name: Collect APKs and ZIPs into artifacts (safe)
        run: |
          set -eux
          ART="$GITHUB_WORKSPACE/artifacts"
          rm -rf "$ART"
          mkdir -p "$ART"

          # Prefer outputs under revanced-magisk/build
          if find revanced-magisk/build -type f \( -iname '*.apk' -o -iname '*.zip' \) -print -quit 2>/dev/null; then
            echo "Collecting from revanced-magisk/build"
            find revanced-magisk/build -type f \( -iname '*.apk' -o -iname '*.zip' \) -exec cp {} "$ART"/ \; || true
          else
            echo "No files in revanced-magisk/build, falling back to revanced-magisk root"
            find revanced-magisk -type f \( -iname '*.apk' -o -iname '*.zip' \) -exec cp {} "$ART"/ \; || true
          fi

          # Count and show what we collected
          COUNT=$(find "$ART" -type f | wc -l)
          echo "collected_count=$COUNT" >> $GITHUB_OUTPUT
          echo "Artifacts folder size and listing:"
          du -sh "$ART" || true
          ls -lh "$ART" || true

      - name: Upload APKs and ZIPs (only if we collected files)
        if: ${{ steps.collect.outputs.collected_count != '0' }}
        uses: actions/upload-artifact@v4
        with:
          name: youtube-build-artifacts
          path: ${{ github.workspace }}/artifacts

      - name: No artifacts found (helpful message)
        if: ${{ steps.collect.outputs.collected_count == '0' }}
        run: |
          echo "No APK or ZIP artifacts were found in revanced-magisk/build or revanced-magisk."
          echo "Check the 'Run build-version.sh' logs; the build printed where it put outputs."
