name: Build YouTube Version (manual)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to pass to build-version.sh (or "auto")'
        required: true
        default: '20.21.37'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Run build-version.sh
        working-directory: revanced-magisk
        run: |
          set -eux
          chmod +x ./build-version.sh
          ./build-version.sh "${{ github.event.inputs.version }}"

      - name: Debug - list all APKs and ZIPs found
        run: |
          echo "Workspace root: $GITHUB_WORKSPACE"
          find revanced-magisk -type f \( -iname '*.apk' -o -iname '*.zip' \) -print0 \
            | xargs -0 du -b --files0-from=- 2>/dev/null \
            | awk '{printf "%12.2f MB %s\n", $1/1024/1024, $2}' \
            | sort -nr || true

      - name: Collect APKs and ZIPs into artifacts
        run: |
          set -eux
          ART="$GITHUB_WORKSPACE/artifacts"
          rm -rf "$ART"
          mkdir -p "$ART"
          # Only search inside revanced-magisk to avoid copying unwanted files
          find revanced-magisk -type f \( -iname '*.apk' -o -iname '*.zip' \) -exec cp {} "$ART"/ \; || true
          echo "Final artifact folder size:"
          du -sh "$ART" || true
          echo "Files in artifact folder:"
          ls -lh "$ART" || true

      - name: Upload APKs and ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: youtube-build-artifacts
          path: ${{ github.workspace }}/artifacts
