name: Upload Release to Telegram

on:
  workflow_run:
    workflows: ["Build Modules"]
    types:
      - completed
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install jq
        run: sudo apt update && sudo apt install jq -y

      - name: Get latest release tag
        id: get_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Get release info
        id: get_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=${{ steps.get_tag.outputs.tag }}
          RELEASE_JSON=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/tags/$RELEASE_TAG")
          echo "$RELEASE_JSON" | jq -r '.body' > body.txt
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat body.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_JSON" > release.json

      - name: Send release notes to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT: -1002692922050
        run: |
          BODY=$(cat body.txt)
          # Process the body similar to your existing sed for Telegram Markdown compatibility, plus escape special Markdown characters
          PROCESSED_BODY=$(echo "$BODY" | sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g; s/^- /↪ /g; /^==/d; s/_/\\_/g; s/\*/\\*/g; s/`/\\`/g')
          NL=$'\n'
          APKS=""
          MODULES=""
          jq -r '.assets[] | .name + "|" + .browser_download_url' release.json | while IFS='|' read -r name url; do
            if [[ $name = *.apk ]]; then
              APKS+="${NL}📦[${name}](${url})"
            elif [[ $name = *.zip ]]; then
              MODULES+="${NL}📦[${name}](${url})"
            fi
          done
          APKS=${APKS#"$NL"}
          MODULES=${MODULES#"$NL"}
          MSG="*New release published!*

          ${PROCESSED_BODY}

          *▼ Download Links:*
          Modules:
          ${MODULES}

          APKs:
          ${APKS}"
          # Truncate if too long (Telegram message limit ~4096 chars)
          MSG=${MSG:0:4000}
          curl -X POST "https://api.telegram.org/bot$TG_TOKEN/sendMessage" \
            -d chat_id="$TG_CHAT" \
            -d parse_mode="Markdown" \
            -d disable_web_page_preview="true" \
            -d text="$MSG"
